export const PRIVATE_CONVERSATION = 'PrivateConversation';
export const PUBLIC_CONVERSATION = 'PublicConversation';
export const GROUP_CONVERSATION = 'GroupConversation';

export const CONNECTION_STATE_PROCESS = 'CONNECTION_STATE_PROCESS';
export const CONNECTION_STATE_ERROR = 'CONNECTION_STATE_ERROR';
export const CONNECTION_STATE_CONNECTED = 'CONNECTION_STATE_CONNECTED';
export const CONNECTION_STATE_NOT_CONNECTED = 'CONNECTION_STATE_NOT_CONNECTED';

export const TYPING_THROTTLE_INTERVAL = 5 * 1000;
export const TYPING_CANCEL_INTERVAL = 7 * 1000;

export const SYMBOL_AVATAR_BG = '#177df2';
export const SYMBOL_AVATAR_COLOR = '#fff';
