global.React        = require 'react'
global.reqwest      = require 'reqwest'
global.EventEmitter = require 'eventEmitter'
global.Pusher       = require 'pusher'
global.moment       = require 'moment'