#!/usr/bin/env bash

git checkout develop
gulp dist
git branch -D dist
git checkout --orphan dist
find . -maxdepth 1 ! -name 'dist' ! -name '.git' ! -name '.*' | xargs rm -rf
rm .??*
mv dist/* ./
rm -rf dist
git add .
git commit -am 'Update static'
git push -u -f origin dist:dist