#!/usr/bin/env bash

npm i
bower i
git pull
gulp dist
find . -maxdepth 1 ! -name 'dist' ! -name '.git' ! -name '.*' | xargs rm -rf
rm .??*
mv dist/* ./
rm -rf dist
git checkout -b dist
git checkout dist
git add .
git commit -am 'Update static'
git push -u -f origin dist:dist