#!/usr/bin/env bash
rm -fr ./bower_components
git branch -D gh-pages
git checkout --orphan gh-pages
git rm -rf ./app
git rm -rf ./utils
#git clean -fd -e dist
git clean -fd
mv dist/* ./
rm -fr ./node_modules
#shopt -s dotglob
git add .
git commit -am 'build gh-pages'
git push -u -f origin gh-pages:gh-pages

