keyMirror = require 'react/lib/keyMirror'

ApiConstants = keyMirror
  SEARCH_LOAD_NEXT_PAGE: null
  EDITOR_CREATE_IMAGE_ATTACHMENT: null
  EDITOR_CREATE_EMBED: null
  EDITOR_CREATE_ENTRY: null
  EDITOR_UPDATE_ENTRY: null
  DESIGN_SAVE: null
  CREATE_BG_IMAGE: null
  LOAD_NOTIFICATIONS: null
  READ_NOTIFICATION: null
  UNFOLLOW_TLOG: null
  UNFOLLOW_TLOG_FROM_YOURSELF: null
  FOLLOW_TLOG: null
  CANCEL_TLOG: null
  IGNORE_TLOG: null
  APPROVE_REQUEST_TLOG: null
  DISAPPROVE_REQUEST_TLOG: null
  VOTE_ENTRY: null
  ADD_TO_FAVORITES_ENTRY: null
  REMOVE_FROM_FAVORITES_ENTRY: null
  ADD_TO_WATCHING_ENTRY: null
  REMOVE_FROM_WATCHING_ENTRY: null
  REPORT_ENTRY: null
  DELETE_ENTRY: null
  ACCEPT_ENTRY: null
  REPOST_ENTRY: null
  DECLINE_ENTRY: null
  LOAD_ENTRIES: null
  LOAD_HTML_ENTRIES: null
  PREDICT_USERS: null
  CREATE_FLOW: null
  UPDATE_FLOW: null
  LOAD_FLOWS: null
  LOAD_MY_FLOWS: null
  ADD_STAFF_FLOW: null
  REMOVE_STAFF_FLOW: null
  CREATE_COMMENT: null
  REPORT_COMMENT: null
  EDIT_COMMENT: null
  DELETE_COMMENT: null

module.exports = ApiConstants