keyMirror = require 'react/lib/keyMirror'

ApiConstants = keyMirror
  SEARCH_LOAD_NEXT_PAGE: null
  FEED_LOAD_ENTRIES: null
  EDITOR_CREATE_IMAGE_ATTACHMENT: null
  EDITOR_CREATE_EMBED: null
  EDITOR_CREATE_ENTRY: null
  EDITOR_UPDATE_ENTRY: null
  DESIGN_SAVE: null
  CREATE_BG_IMAGE: null
  LOAD_NOTIFICATIONS: null
  READ_NOTIFICATION: null
  UNFOLLOW_TLOG: null
  FOLLOW_TLOG: null
  CANCEL_TLOG: null
  VOTE_ENTRY: null
  LOAD_LIVE_ENTRIES: null
  LOAD_FRIENDS_ENTRIES: null
  LOAD_BEST_ENTRIES: null
  LOAD_ANONYMOUS_ENTRIES: null
  ACCEPT_ENTRY: null
  DECLINE_ENTRY: null

module.exports = ApiConstants